### ISSUE TITLE
Is this plugins support AndroidX?

### ISSUE THREAD

**Issue by bigbirdhzp** [wenerme/drifter#2]

**Comment by wenerme** [comment]
I think it should works on android x, do you get any exception on android x?

**Comment by bigbirdhzp** [comment]
Yes.I use your plugin in my flutter example(without adapted to Android X),it works successfully.But An error occurred in other flutter example(have adapted Android X).

![image](https://user-images.githubusercontent.com/22903159/61838953-4370dc80-aebe-11e9-8a67-5c6a10b671d3.png)

I am sure i have adapted Android X in my flutter example.So I check your source code,  I find the .java file stilling using "android.support" package.

![image](https://user-images.githubusercontent.com/22903159/61839334-bdee2c00-aebf-11e9-80fb-6e395c8cd6c7.png)
 
I check some data by google, the "andorid.support" package should replaced by "androidx.core" package. 

I try to mirate this plugin to AndroidX, but failed.I am not an Android developer, So I dont' know how to update this plugin.

I  set the flutter example to adapted androidX： 
1、android/gradle/wrapper/gradle-wrapper.propertie：
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

2、android/build.gradle：
dependencies {
    classpath 'com.android.tools.build:gradle:3.3.0'
}

testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

androidTestImplementation 'androidx.test:runner:1.1.1'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'

3、android/gradle.properties：
android.enableJetifier=true
android.useAndroidX=true

Then I find the plugins is not support AndoridX.

If you are chinese, you can check this website:
https://blog.csdn.net/ocean20/article/details/89215290
https://blog.csdn.net/yin_ol/article/details/89421390
